"""modification enigmes de la semaine

Revision ID: 39b77e7e548f
Revises: d940e1bb38fe
Create Date: 2025-08-12 11:07:12.087294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39b77e7e548f'
down_revision = 'd940e1bb38fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_val_to_find', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nb_item', sa.Integer(), nullable=True))
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', mysql.JSON(), nullable=False))
        batch_op.drop_column('nb_item')
        batch_op.drop_column('nb_val_to_find')

    # ### end Alembic commands ###
