"""Ajoute de la table week_problems

Revision ID: d940e1bb38fe
Revises: c2bc621ed8c9
Create Date: 2025-08-08 16:43:06.071729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd940e1bb38fe'
down_revision = 'c2bc621ed8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nb_question', sa.Integer(), nullable=True),
    sa.Column('figure_path', sa.Text(), nullable=True),
    sa.Column('question', sa.JSON(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('values_list', sa.JSON(), nullable=True),
    sa.Column('solution', sa.JSON(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tutorial_mojette_done',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tutorial_mojette_done',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    op.drop_table('week_problem')
    # ### end Alembic commands ###
