"""Initial migration

Revision ID: e9e953fd9557
Revises: 
Create Date: 2025-03-17 01:07:47.665494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e953fd9557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formation_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('category_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mojette_shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('array_box', sa.Text(), nullable=False),
    sa.Column('nb_bin_down', sa.Integer(), nullable=False),
    sa.Column('nb_bin_left', sa.Integer(), nullable=False),
    sa.Column('nb_bin_right', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('region_code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('viewBox', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('confirmation_token', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tutorial_mojette_done', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('mojettes', sa.Integer(), nullable=True),
    sa.Column('token_coin', sa.Integer(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('stripe_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('carre_list', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkout_session',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('department',
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('zones', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['region.region_code'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('formation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('img_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['formation_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mojette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('shape', sa.Integer(), nullable=True),
    sa.Column('bin_values', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ),
    sa.ForeignKeyConstraint(['shape'], ['mojette_shape.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward',
    sa.Column('game', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.Column('help_1_percent_cost', sa.Integer(), nullable=True),
    sa.Column('help_2_percent_cost', sa.Integer(), nullable=True),
    sa.Column('help_3_percent_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ),
    sa.PrimaryKeyConstraint('game', 'level')
    )
    op.create_table('carre_completed',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('completion_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['carre.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'grid_id')
    )
    op.create_table('formation_availability',
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('formation_availability_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('live_link', sa.Text(), nullable=True),
    sa.Column('replay_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.PrimaryKeyConstraint('formation_availability_id')
    )
    op.create_table('formation_bought',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'formation_id')
    )
    op.create_table('mojette_completed',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('helps_used', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('completion_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['mojette.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'grid_id')
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('question', sa.JSON(), nullable=False),
    sa.Column('nb_question', sa.Integer(), nullable=True),
    sa.Column('help_1', sa.Text(), nullable=True),
    sa.Column('help_2', sa.Text(), nullable=True),
    sa.Column('help_3', sa.Text(), nullable=True),
    sa.Column('figure_path', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('values_list', sa.JSON(), nullable=True),
    sa.Column('solution', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.number'], ),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ),
    sa.ForeignKeyConstraint(['type'], ['problem_type.id'], ),
    sa.PrimaryKeyConstraint('id', 'department', 'type')
    )
    op.create_table('problem_completed',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('helps_used', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'problem_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_completed')
    op.drop_table('problem')
    op.drop_table('mojette_completed')
    op.drop_table('formation_bought')
    op.drop_table('formation_availability')
    op.drop_table('carre_completed')
    op.drop_table('reward')
    op.drop_table('mojette')
    op.drop_table('formation')
    op.drop_table('department')
    op.drop_table('checkout_session')
    op.drop_table('carre')
    op.drop_table('user')
    op.drop_table('region')
    op.drop_table('problem_type')
    op.drop_table('mojette_shape')
    op.drop_table('game')
    op.drop_table('formation_category')
    # ### end Alembic commands ###
