
export interface TutorialStep {
  descriptionTitle: string;
  description: string;
  instructions: string;
  gridVisible: boolean;
  image: string;
  gridActive: boolean;
  hideBin: boolean;
  tilesToFill: number[]; //index des cases qu'on doit remplir a cette etape
  tileNumbers: Array<{ tileId: number; value: number; color: string }>;
  bins: Array<[direction: 'left' | 'right' | 'down', id: number]>;
}

export const tutorialSteps: TutorialStep[] = [
    {
      descriptionTitle: "Tutoriel Mojette",
      description: "Bienvenue dans le tutoriel du Jeu Mojette.",
      instructions: "",
      image: "",
      gridVisible: false,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Règle n°1:",
      description: "Chaque case contient un chiffre de 0 à 9.",
      instructions: "Avant de commencer, les 3 règles du Jeu Mojette",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [
        { tileId: 18, value: 11, color: 'red' },
        { tileId: 23, value: 8, color: 'green' }
      ],
      bins: [],
    },
    {
      descriptionTitle: "Règle n°2:",
      description: `Chaque projection, qu’elle soit <b>verticale (90°)</b> ou diagonale (45° ou 135°), indique la somme des chiffres présents dans les cases qu’elle traverse.`,
      instructions: "Avant de commencer, les 3 règles du Jeu Mojette",
      image: "tuto1.png",
      gridVisible: false,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Règle n°2:",
      description: `Chaque projection, qu’elle soit verticale (90°) ou <b>diagonale (45° ou 135°)</b>, indique la somme des chiffres présents dans les cases qu’elle traverse.`,
      instructions: "Avant de commencer, les 3 règles du Jeu Mojette",
      image: "tuto2.png",
      gridVisible: false,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Règle n°2:",
      description: `Chaque projection, qu’elle soit <b>verticale (90°) ou diagonale (45° ou 135°)</b>, indique la somme des chiffres présents dans les cases qu’elle traverse.`,
      instructions: "Avant de commencer, les 3 règles du Jeu Mojette",
      image: "tuto3.png",
      gridVisible: false,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Règle n°3:",
      description: "Il ne peut y avoir que trois chiffres différents par grille.",
      instructions: "Avant de commencer, les 3 règles du Jeu Mojette",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [
        { tileId: 9, value: 1, color: 'green' },
        { tileId: 15, value: 2, color: 'green' },
        { tileId: 24, value: 3, color: 'green' },
        { tileId: 38, value: 4, color: 'red' }
      ],
      bins: [],
    },
    {
      descriptionTitle: "Première partie du jeu",
      description: "Trouver les 3 chiffres qui composent la grille.",
      instructions: "",
      image: "",
      gridVisible: false,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "",
      description: "",
      instructions: "Remplir la case violette pour que la somme de la projection soit égale à 0.",
      image: "",
      gridVisible: true,
      gridActive: true,
      hideBin: false,
      tilesToFill: [21],
      tileNumbers: [],
      bins: [['down', 0]],
    },
    {
      descriptionTitle: "",
      description: "",
      instructions: "Remplir la case violette pour que la somme de la projection soit égale à 0.",
      image: "",
      gridVisible: true,
      gridActive: true,
      hideBin: false,
      tilesToFill: [27],
      tileNumbers: [],
      bins: [['down', 6]],
    },
    {
      descriptionTitle: "",
      description: "On note que lorsque l’on remplit une case de la grille, chaque projection associée (ici, verticale) se calcule automatiquement.",
      instructions: "",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      bins: [
        ['down', 0],
        ['down', 6]
      ],
      tileNumbers: []
    },
    {
      descriptionTitle: "",
      description: "",
      instructions: "Remplir les cases violettes pour que la somme de la projection soit égale à 0.",
      image: "",
      gridVisible: true,
      gridActive: true,
      hideBin: false,
      tilesToFill: [11, 18, 25, 32, 39],
      tileNumbers: [],
      bins: [['down', 4]],
    },
    {
      descriptionTitle: "",
      description: `Il existe 3 possibilités pour remplir les cases violettes en prenant en compte la règle n°1 (chaque case contient un chiffre de 0 à 9). <br> 18 = 8+8+2 <br> 18 = 9+9+0 <br> 18 = 6+6+6`,
      instructions: "",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [15, 22, 29],
      tileNumbers: [],
      bins: [['down', 1]],
    },
    {
      descriptionTitle: "18 = 8 + 8 + 2",
      description: "Cette solution n’est pas possible, car elle ne respecte par la règle n°3 du jeu (pas plus de 3 chiffres par grille). Or, on a déjà trouvés les chiffres 0 et 1.",
      instructions: "",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [
        { tileId: 15, value: 8, color: 'red' },
        { tileId: 22, value: 8, color: 'red' },
        { tileId: 29, value: 2, color: 'red' },
      ],
      bins: [['down', 1]],
    },
    {
      descriptionTitle: "18=9+9+0 \n 18=6+6+6",
      description: "Les deux solutions restantes semblent possibles car elles respectent les règles n°1 et n°3. Il va donc falloir regarder au niveau de la règle n°2 pour trouver la bonne solution.",
      instructions: "",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [15, 22, 29],
      tileNumbers: [],
      bins: [['down', 1]],
    },
    {
      descriptionTitle: "RAPPEL DE LA Règle n°2",
      description: "Chaque projection, qu’elle soit verticale (90°) ou diagonale (45° ou 135°), indique la somme des chiffres présents dans les cases qu’elle traverse.",
      instructions: "",
      image: "tuto3.png",
      gridVisible: false,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [
      ],
      bins: [],
    },
    {
      descriptionTitle: "18 = 9 + 9 + 0",
      description: "Cette solution n’est pas possible, car elle imposerait qu’au moins une des sommes des projections diagonales soit >= à 9. Or ce n’est pas le cas ici.",
      instructions: "",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [
        { tileId: 15, value: 9, color: 'red' },
        { tileId: 22, value: 9, color: 'red' },
        { tileId: 29, value: 0, color: 'red' },
      ],
      bins: [
        ['down', 1],
        ['left', 4],
        ['left', 5],
        ['left', 6],
        ['right', 0],
        ['right', 1],
        ['right', 2],
      ],
    },
    {
      descriptionTitle: "18 = 6 + 6 + 6",
      description: "Cette solution est donc la bonne car elle respecte les 3 règles du Jeu Mojette. Remplir les cases violettes pour que la somme de la projection (18) soit égale à 0.",
      instructions: "Remplir les cases violettes pour que la somme de la projection soit égale à 0.",
      gridVisible: true,
      image: "",
      gridActive: true,
      hideBin: false,
      tilesToFill: [15, 22, 29],
      tileNumbers: [],
      bins: [['down', 1]],
    },
    {
      descriptionTitle: "",
      description: "Comme expliqué précédemment dans le tutoriel, on remarque que les sommes des projections se mettent à jour en fonction des données entrées dans les cases de la grille.",
      instructions: "",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [
        ['down', 1],
        ['left', 4],
        ['left', 5],
        ['left', 6],
        ['right', 0],
        ['right', 1],
        ['right', 2],
      ],
    },
    {
      descriptionTitle: "",
      description: "À ce stade on a obtenu les 3 chiffres qui composent la grille (0; 1; 6). On doit donc pouvoir remplir facilement le reste de la grille.",
      instructions: "",
      image: "",
      gridVisible: true,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Finir de remplir la grille",
      description: "",
      instructions: "Remplir les cases violettes pour que la somme des projections soit égale à 0.",
      image: "",
      gridVisible: true,
      gridActive: true,
      hideBin: false,
      tilesToFill: [10, 16],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Finir de remplir la grille",
      description: "",
      instructions: "Remplir les cases violettes pour que la somme des projections soit égale à 0.",
      image: "",
      gridVisible: true,
      gridActive: true,
      hideBin: false,
      tilesToFill: [17, 23, 24, 31],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Finir de remplir la grille",
      description: "",
      instructions: "Remplir les cases violettes pour que la somme des projections soit égale à 0.",
      image: "",
      gridVisible: true,
      gridActive: true,
      hideBin: false,
      tilesToFill: [3, 19, 26, 30, 33, 38],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Finir de remplir la grille",
      description: "",
      instructions: "Remplir les cases violettes pour que la somme des projections soit égale à 0.",
      image: "",
      gridVisible: true,
      gridActive: true,
      hideBin: false,
      tilesToFill: [9, 37],
      tileNumbers: [],
      bins: [],
    },
    {
      descriptionTitle: "Félicitations !",
      description: `Vous avez terminé le tutoriel du Jeu Mojette !`,
      image: "",
      instructions: "",
      gridVisible: false,
      gridActive: false,
      hideBin: false,
      tilesToFill: [],
      tileNumbers: [],
      bins: [],
    },
  ];